name: Auto Scrape Live Stream Link

on:
  # schedule:
  #   - cron: '0 */3 * * *'
  workflow_dispatch:
    # YAHAN HUMNE INPUT BOX ADD KIYA HAI
    inputs:
      target_url:
        description: 'Match/Channel ka Pura Link dalein (e.g., https://crichd.com.co/willow...)'
        required: true
        default: 'https://crichd.com.co/willow-cricket-live-streaming'

jobs:
  scrape-and-update:
    runs-on: ubuntu-latest
    permissions:
      contents: write 

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install Tools
        run: npm install

      - name: Code Run Karein (Scraping)
        # YAHAN INPUT WALA LINK SCRIPT KO PASS HO RAHA HAI
        env:
          TARGET_URL: ${{ github.event.inputs.target_url }}
        run: node scraper.js

      - name: Save Naya Link (Commit & Push)
        run: |
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'actions@github.com'
          touch stream-data.json # Error 128 fix: file na hone par force create karega
          git add stream-data.json
          git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update stream link" && git push)











# name: Auto Scrape Live Stream Link

# on:
#   schedule:
#     # Yeh job har 3 ghante baad chalegi
#     - cron: '0 */3 * * *'
#   workflow_dispatch: # Yeh manual button ke liye hai

# jobs:
#   scrape-and-update:
#     runs-on: ubuntu-latest

#     permissions:
#       contents: write # GitHub ko files change karne ki ijazat dena

#     steps:
#       - name: Checkout Repository
#         uses: actions/checkout@v4

#       - name: Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '20'

#       - name: Install Tools
#         run: npm install

#       - name: Code Run Karein (Scraping)
#         run: node scraper.js

#       - name: Save Naya Link (Commit & Push)
#         run: |
#           git config --global user.name 'GitHub Actions Bot'
#           git config --global user.email 'actions@github.com'
#           git add stream-data.json
#           # Agar naya link purane se mukhtalif hai, tabhi save (commit) karo
#           git diff --quiet && git diff --staged --quiet || (git commit -m "Auto-update stream link" && git push)
